-- MySQL Script generated by MySQL Workbench
-- Thu Apr 14 16:49:21 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id_user` CHAR(36) NOT NULL,
  `username` VARCHAR(14) NOT NULL,
  `date_joined` DATETIME NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`post` ;

CREATE TABLE IF NOT EXISTS `mydb`.`post` (
  `id_post` CHAR(36) NOT NULL,
  `post` VARCHAR(777) NOT NULL,
  `date_time` DATETIME NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`id_post`),
  INDEX `fk_post_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_follows_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_follows_user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_follows_user` (
  `user_id` CHAR(36) NOT NULL,
  `follows_user_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`user_id`, `follows_user_id`),
  INDEX `fk_user_has_user_user1_idx` (`follows_user_id` ASC) VISIBLE,
  INDEX `fk_user_has_user_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_user_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_user_user1`
    FOREIGN KEY (`follows_user_id`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`repost`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`repost` ;

CREATE TABLE IF NOT EXISTS `mydb`.`repost` (
  `id_repost` CHAR(36) NOT NULL,
  `post_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`id_repost`),
  INDEX `fk_repost_post1_idx` (`post_id` ASC) VISIBLE,
  INDEX `fk_repost_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_repost_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `mydb`.`post` (`id_post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repost_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
